/**
 * Renders the recorded-shape fixture files in `src/google/fixtures/*.json`
 * (issue #130, requirement 5).
 *
 * The adapter (#125) tests against these files; they are generated by
 * driving the ACTUAL fake server over `app.request()` — a response the fake
 * would give is written verbatim — so the server and the fixtures cannot
 * drift. `fixtureFiles.test.ts` regenerates them in-memory on every test
 * run and fails when the checked-in files differ; regenerate with:
 *
 *     pnpm --filter @wellregarded/sources gen:google-fixtures
 *
 * Determinism: seed 42, and the store clock pinned to `FIXTURE_EPOCH`, so
 * output is byte-identical across machines and time.
 */

import { createFakeGbp } from "./app.js";
import { FIXTURE_EPOCH, generateFixturePractice } from "./fixtures.js";
import { FakeGbpStore } from "./store.js";

export const GOOGLE_FIXTURE_SEED = 42;

/** Render every fixture file: filename → JSON content (trailing newline). */
export async function renderGoogleFixtureFiles(): Promise<
  Record<string, string>
> {
  const store = new FakeGbpStore({ clock: () => Date.parse(FIXTURE_EPOCH) });
  const { app } = createFakeGbp(store);
  generateFixturePractice(store, {
    locations: 2,
    reviewsPerLocation: 15,
    seed: GOOGLE_FIXTURE_SEED,
  });
  // A location with zero reviews, for the empty-page fixture.
  store.addLocation({ title: "Cedar Ridge Dental — Annex (no reviews yet)" });

  const files: Record<string, string> = {};
  const record = async (name: string, response: Response): Promise<void> => {
    if (!response.ok) {
      throw new Error(
        `fixture request for ${name} failed: ${response.status} ${await response.text()}`,
      );
    }
    files[name] = `${JSON.stringify(await response.json(), null, 2)}\n`;
  };

  // OAuth: code exchange then refresh — deterministic fake tokens.
  const code = store.issueAuthCode();
  await record(
    "oauth.token.json",
    await app.request("/oauth/token", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({
        grant_type: "authorization_code",
        code,
        client_id: "fake-client",
        client_secret: "fake-secret",
        redirect_uri: "http://localhost/callback",
      }).toString(),
    }),
  );

  const token = store.issueAccessToken();
  const get = (path: string) =>
    app.request(path, { headers: { Authorization: `Bearer ${token}` } });

  await record("accounts.list.json", await get("/v1/accounts"));
  await record(
    "locations.list.json",
    await get("/v1/accounts/1/locations?readMask=*&pageSize=100"),
  );
  await record("location.get.json", await get("/v1/locations/1?readMask=*"));

  // Reviews: pageSize 10 over 15 reviews forces a two-page walk, so the
  // fixtures pin real pagination mechanics (nextPageToken shape included).
  const page1Response = await get(
    "/v4/accounts/1/locations/1/reviews?pageSize=10",
  );
  const page1 = (await page1Response.clone().json()) as {
    nextPageToken?: string;
  };
  await record("reviews.list.page1.json", page1Response);
  if (!page1.nextPageToken) {
    throw new Error("expected page 1 of 15 reviews to carry a nextPageToken");
  }
  await record(
    "reviews.list.page2.json",
    await get(
      `/v4/accounts/1/locations/1/reviews?pageSize=10&pageToken=${encodeURIComponent(page1.nextPageToken)}`,
    ),
  );
  await record(
    "reviews.list.empty.json",
    await get("/v4/accounts/1/locations/3/reviews"),
  );

  // Reply upsert response — including the 2026 moderation field
  // (`reviewReplyState`) #127 must record from the PUT.
  await record(
    "reviews.updateReply.json",
    await app.request("/v4/accounts/1/locations/1/reviews/1/reply", {
      method: "PUT",
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        comment:
          "Thank you for the feedback — we'd love to make this right. Please call our office manager at (616) 555-0142.",
      }),
    }),
  );

  return files;
}
